name: firstWorkflow
on: workflow_dispatch
jobs: 
  first_job: 
    runs-on: ubuntu-latest
    steps: 
      -name: afficher bonjour
        run: echo"salut tout le monde"
      -name: dire good luck
        run: echo"bon stage"
        
      
